/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.angelStudio.panel;

/**
 *
 * @author Oshadi
 */
public class ManageCameraType extends javax.swing.JPanel {

    /**
     * Creates new form ManageCameraType
     */
    public ManageCameraType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtDesigneType = new javax.swing.JTextField();
        lblDesigneID = new javax.swing.JLabel();
        lblDesigneSave = new javax.swing.JLabel();
        lbDesigneUpdate = new javax.swing.JLabel();
        lblDesigneRemove = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 220, 30));
        add(txtDesigneType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 220, 30));

        lblDesigneID.setBackground(new java.awt.Color(0, 204, 204));
        lblDesigneID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDesigneID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesigneID.setText("S");
        lblDesigneID.setOpaque(true);
        add(lblDesigneID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 30, 30));

        lblDesigneSave.setBackground(new java.awt.Color(0, 204, 204));
        lblDesigneSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDesigneSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesigneSave.setText("Save");
        lblDesigneSave.setOpaque(true);
        add(lblDesigneSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 30));

        lbDesigneUpdate.setBackground(new java.awt.Color(0, 204, 204));
        lbDesigneUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDesigneUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDesigneUpdate.setText("Update");
        lbDesigneUpdate.setOpaque(true);
        add(lbDesigneUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 100, 30));

        lblDesigneRemove.setBackground(new java.awt.Color(0, 204, 204));
        lblDesigneRemove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDesigneRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesigneRemove.setText("Remove");
        lblDesigneRemove.setOpaque(true);
        add(lblDesigneRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Camera ID", "Camera Type"
            }
        ));
        jTable1.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 360, 130));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Designe Type");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Designe ID");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbDesigneUpdate;
    private javax.swing.JLabel lblDesigneID;
    private javax.swing.JLabel lblDesigneRemove;
    private javax.swing.JLabel lblDesigneSave;
    private javax.swing.JTextField txtDesigneType;
    // End of variables declaration//GEN-END:variables
}
