/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.angelStudio.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.edu.angelStudio.controller.ManageCameraController;
import lk.ijse.edu.angleStudio.model.ReturnItemDTO;

/**
 *
 * @author acer
 */
public class ManageReturnItem extends javax.swing.JFrame {

    /**
     * Creates new form ManageReturnItem
     */
    public ManageReturnItem() {
        initComponents();
        loodAllReturn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtdamages = new javax.swing.JTextField();
        txtCustomerNic = new javax.swing.JTextField();
        txtCusomername = new javax.swing.JTextField();
        tctCustomerId = new javax.swing.JTextField();
        txtFullTotal = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        txtCameraprice = new javax.swing.JTextField();
        txtPayAmount = new javax.swing.JTextField();
        txtBlance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtReturnOid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCamId = new javax.swing.JTextField();
        txtCamName = new javax.swing.JTextField();
        txtlensBrand = new javax.swing.JTextField();
        txtlensSize = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReturn = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1060, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(59, 163, 163));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("                                                                        Manage Return Item");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Damages");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Customer NIC");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Customer Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Customer Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, 20));
        jPanel1.add(txtdamages, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 300, 40));

        txtCustomerNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNicActionPerformed(evt);
            }
        });
        jPanel1.add(txtCustomerNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 150, 20));
        jPanel1.add(txtCusomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 150, -1));
        jPanel1.add(tctCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 150, -1));
        jPanel1.add(txtFullTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 150, -1));
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 150, -1));
        jPanel1.add(txtCameraprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 150, 20));
        jPanel1.add(txtPayAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 150, -1));
        jPanel1.add(txtBlance, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Balance");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 140, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Pay Amount");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 140, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Full Total");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Qty");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 140, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Camara Price");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 140, 20));

        jLabel12.setBackground(new java.awt.Color(59, 163, 163));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Manage Return Item");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Order Id");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 140, 20));
        jPanel1.add(txtReturnOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 150, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Camera ID");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 140, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Camera Name");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 140, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Lens Brand");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 140, 20));

        jLabel17.setBackground(new java.awt.Color(0, 204, 204));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Save And Print");
        jLabel17.setOpaque(true);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 170, 30));
        jPanel1.add(txtCamId, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 150, -1));
        jPanel1.add(txtCamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 150, -1));
        jPanel1.add(txtlensBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 150, -1));
        jPanel1.add(txtlensSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 150, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Lens Size");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 140, 20));

        jLabel23.setBackground(new java.awt.Color(0, 153, 153));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Payment  Details");
        jLabel23.setOpaque(true);
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 320, 30));

        jLabel24.setBackground(new java.awt.Color(0, 153, 153));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Customer Details");
        jLabel24.setOpaque(true);
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 320, 30));

        jLabel25.setBackground(new java.awt.Color(0, 153, 153));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Camera Details");
        jLabel25.setOpaque(true);
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 320, 30));

        tableReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer NIC", "Customer Name", "Customer Id", "Order Id", "Camera id", "Camera Name", "Lens Brand", "Lens Size", "Camera price", "qty", "Full Total", "Pay Amount", "Balance"
            }
        ));
        jScrollPane1.setViewportView(tableReturn);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 1010, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1040, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNicActionPerformed
        try {
            String nic=txtCustomerNic.getText();
            ReturnItemDTO returnItemDTO=ManageCameraController.SearchBuNic(nic);
            txtCusomername.setText(returnItemDTO.getName());
            tctCustomerId.setText(returnItemDTO.getCid());
            txtReturnOid.setText(returnItemDTO.getOid());
            txtCamId.setText(returnItemDTO.getCaid());
            txtCamName.setText(returnItemDTO.getBrand());
            txtlensBrand.setText(returnItemDTO.getLenseBrand());
            txtlensSize.setText(returnItemDTO.getLenseSize());
            txtCameraprice.setText(""+returnItemDTO.getPrice());
            txtQty.setText(""+returnItemDTO.getQty());
            txtFullTotal.setText(""+returnItemDTO.getFullTotal());
            txtPayAmount.setText(""+returnItemDTO.getPayAmount());
            txtBlance.setText(""+returnItemDTO.getBlance());
        } catch (Exception ex) {
            Logger.getLogger(ManageReturnItem.class.getName()).log(Level.SEVERE, null, ex);
        }
     
     
     
     
     
     
     
    }//GEN-LAST:event_txtCustomerNicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageReturnItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageReturnItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageReturnItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageReturnItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageReturnItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReturn;
    private javax.swing.JTextField tctCustomerId;
    private javax.swing.JTextField txtBlance;
    private javax.swing.JTextField txtCamId;
    private javax.swing.JTextField txtCamName;
    private javax.swing.JTextField txtCameraprice;
    private javax.swing.JTextField txtCusomername;
    private javax.swing.JTextField txtCustomerNic;
    private javax.swing.JTextField txtFullTotal;
    private javax.swing.JTextField txtPayAmount;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtReturnOid;
    private javax.swing.JTextField txtdamages;
    private javax.swing.JTextField txtlensBrand;
    private javax.swing.JTextField txtlensSize;
    // End of variables declaration//GEN-END:variables

    private void loodAllReturn() {
        
        try {
            ArrayList<ReturnItemDTO>returnItem=ManageCameraController.getAllReturn();
            DefaultTableModel dtm=(DefaultTableModel) tableReturn.getModel();
            dtm.setRowCount(0);
            for (ReturnItemDTO returnItemDTO: returnItem) {
                Object[] rowData={
                    returnItemDTO.getNIC(),
                    returnItemDTO.getName(),
                    returnItemDTO.getCid(),
                    returnItemDTO.getOid(),
                    returnItemDTO.getCaid(),
                    returnItemDTO.getBrand(),
                    returnItemDTO.getLenseBrand(),
                    returnItemDTO.getLenseSize(),
                    returnItemDTO.getPrice(),
                    returnItemDTO.getQty(),
                    returnItemDTO.getFullTotal(),
                    returnItemDTO.getPayAmount(),
                    returnItemDTO.getBlance()
                };
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageReturnItem.class.getName()).log(Level.SEVERE, null, ex);
        }
}
}
