/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.angelStudio.view;


import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.edu.angelStudio.controller.ManageCameraController;
import lk.ijse.edu.angelStudio.entity.Camara;
import lk.ijse.edu.angleStudio.model.CamaraDTO;


/**
 *
 * @author Oshadi
 */
public class ManageCamera extends javax.swing.JFrame {

    String check3 = "Flashers";
    String Remote="Remote Controol";
    String wifi="WiFy";
    String bloototh="Bloototh";
    String usb="USB";

    /**
     * Creates new form ManageDesigne
     */
    public ManageCamera() {
        initComponents();
        setLocationRelativeTo(null);
        loardAllCategory();
        loardAllCamaras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDesigneID = new javax.swing.JTextField();
        txtDesigneCamerColur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDesigneID = new javax.swing.JLabel();
        lblDesigneSave = new javax.swing.JLabel();
        lbDesigneUpdate = new javax.swing.JLabel();
        lblDesigneRemove = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDesigneLenseSize = new javax.swing.JTextField();
        txtDesigneLenseBrand = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDesignePixel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDesigneLenseType = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDesigneBatreyVoltage = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        comboCategory = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtDesigneBodyType = new javax.swing.JTextField();
        txtDesigneBrand = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtDesigneBatreyDuration = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDesigneBattryType = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDesignePrice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDesigneQTY = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDesigne = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(59, 163, 163));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Camera");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 50));
        jPanel1.add(txtDesigneID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 190, 30));
        jPanel1.add(txtDesigneCamerColur, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 220, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Camer Colur");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Camer ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 30));

        lblDesigneID.setBackground(new java.awt.Color(0, 204, 204));
        lblDesigneID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDesigneID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesigneID.setText("S");
        lblDesigneID.setOpaque(true);
        jPanel1.add(lblDesigneID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 30, 30));

        lblDesigneSave.setBackground(new java.awt.Color(0, 204, 204));
        lblDesigneSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDesigneSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesigneSave.setText("Save");
        lblDesigneSave.setOpaque(true);
        lblDesigneSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDesigneSaveMouseClicked(evt);
            }
        });
        jPanel1.add(lblDesigneSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 100, 30));

        lbDesigneUpdate.setBackground(new java.awt.Color(0, 204, 204));
        lbDesigneUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDesigneUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDesigneUpdate.setText("Update");
        lbDesigneUpdate.setOpaque(true);
        lbDesigneUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDesigneUpdateMouseClicked(evt);
            }
        });
        jPanel1.add(lbDesigneUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 100, 30));

        lblDesigneRemove.setBackground(new java.awt.Color(0, 204, 204));
        lblDesigneRemove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDesigneRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesigneRemove.setText("Remove");
        lblDesigneRemove.setOpaque(true);
        lblDesigneRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDesigneRemoveMouseClicked(evt);
            }
        });
        jPanel1.add(lblDesigneRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, 100, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Lense Size");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 100, 30));
        jPanel1.add(txtDesigneLenseSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 220, 30));
        jPanel1.add(txtDesigneLenseBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 220, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Lense Brand");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Lense Pixel");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 100, 30));
        jPanel1.add(txtDesignePixel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 220, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Lense type");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 100, 30));
        jPanel1.add(txtDesigneLenseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 220, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Camer Category");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 100, 30));
        jPanel1.add(txtDesigneBatreyVoltage, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 220, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Batrey Voltage");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 100, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Others :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 100, 50));

        jPanel1.add(comboCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 220, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Body Type");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 30));
        jPanel1.add(txtDesigneBodyType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 220, 30));
        jPanel1.add(txtDesigneBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 220, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Camer Brand");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 30));

        jLabel23.setBackground(new java.awt.Color(0, 153, 153));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Camer Campany");
        jLabel23.setOpaque(true);
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 30));

        jLabel24.setBackground(new java.awt.Color(0, 153, 153));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Camera Batrey");
        jLabel24.setOpaque(true);
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 320, 30));

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setText("Remote Controol");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Attrchments :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 100, 40));

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setText("Flashers");
        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
        });
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox4.setText("Wifi");
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, -1));

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox5.setText("Bloototh");
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, -1, -1));

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox6.setText("USB");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        jLabel26.setBackground(new java.awt.Color(0, 153, 153));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Others");
        jLabel26.setOpaque(true);
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 320, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Batrey Duration");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 100, 30));
        jPanel1.add(txtDesigneBatreyDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 220, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Batrey Type");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 100, 30));
        jPanel1.add(txtDesigneBattryType, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 220, 30));

        jLabel29.setBackground(new java.awt.Color(0, 153, 153));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Camer Lense");
        jLabel29.setOpaque(true);
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 320, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Price");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 30));
        jPanel1.add(txtDesignePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 220, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("QTY");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 100, 30));
        jPanel1.add(txtDesigneQTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 220, 30));

        tblDesigne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Camera ID", "Camer Brand", "Body Type", "Camer Colur", "Lense Type", "Lense Pixel", "Lense  Brand", "Lense Size", "Price", "QTY"
            }
        ));
        jScrollPane3.setViewportView(tblDesigne);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 1000, 230));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Company");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, 30));
        jPanel1.add(txtCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked

        
    }//GEN-LAST:event_jCheckBox3MouseClicked

    private void lblDesigneSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDesigneSaveMouseClicked
        String Flashers;
        String RemotControol;
        String other1;
        String other2;
        String other3;
        try {
            String camaraId = txtDesigneID.getText();
            String brand = txtDesigneBrand.getText();
            String compuny = txtCompany.getText();
            String bodyT = txtDesigneBodyType.getText();
            String colur=txtDesigneCamerColur.getText();
            String lenseType=txtDesigneLenseType.getText();
            String pixel=txtDesignePixel.getText();
            boolean selected = jCheckBox3.isSelected();
            if (selected) {
                 Flashers=check3;
            }else{
                 Flashers=null;
            }
            boolean selected1 = jCheckBox2.isSelected();
            if (selected) {
                 RemotControol=Remote;
            }else{
                 RemotControol=null;
                
            }
            boolean selected2 = jCheckBox4.isSelected();
            if (selected) {
                 other1=wifi;
            }else{
                 other1=null;
            }
            boolean selected13 = jCheckBox5.isSelected();
            if (selected) {
                 other2=bloototh;
            }else{
                 other2=null;
                
            }
            boolean selected4 = jCheckBox5.isSelected();
            if (selected) {
                 other3=usb;
            }else{
                 other3=null;
            }
            String  battryVotage=txtDesigneBatreyVoltage.getText();
            String battryDeu=txtDesigneBatreyDuration.getText();
            String battryType=txtDesigneBattryType.getText();
            String lenseBrand=txtDesigneLenseBrand.getText();
            String lenseSize=txtDesigneLenseBrand.getText();
            int qty=Integer.parseInt(txtDesigneQTY.getText());
            double price=Double.parseDouble(txtDesignePrice.getText());
            CamaraDTO camara=new CamaraDTO(camaraId,brand,compuny,bodyT,colur,lenseType,pixel,Flashers,RemotControol,other1,other2,other3,battryVotage,battryDeu,battryType,lenseBrand,lenseSize,qty,price);
            boolean isAdded=ManageCameraController.saveaaaa(camara);
            if (isAdded) {
                JOptionPane.showMessageDialog(null,"Camara Is Add");
            }
            loardAllCamaras();
        } catch (Exception ex) {
            Logger.getLogger(ManageCamera.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblDesigneSaveMouseClicked

    private void lblDesigneRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDesigneRemoveMouseClicked
        try {
            if(tblDesigne.getSelectedRow()== -1){
                JOptionPane.showMessageDialog(null,"Selected Row");
            }
            boolean isDelete=ManageCameraController.delete(tblDesigne.getValueAt(tblDesigne.getSelectedRow(), 0).toString());
            if(isDelete){
                JOptionPane.showMessageDialog(null,"Delete is SuccessFull");
            }
            loardAllCamaras();
        } catch (Exception ex) {
            Logger.getLogger(ManageCamera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblDesigneRemoveMouseClicked

    private void lbDesigneUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDesigneUpdateMouseClicked
        try {
            String Flashers;
            String RemotControol;
            String other1;
            String other2;
            String other3;
            
            String camaraId = txtDesigneID.getText();
            String brand = txtDesigneBrand.getText();
            String compuny = txtCompany.getText();
            String bodyT = txtDesigneBodyType.getText();
            String colur=txtDesigneCamerColur.getText();
            String lenseType=txtDesigneLenseType.getText();
            String pixel=txtDesignePixel.getText();
            boolean selected = jCheckBox3.isSelected();
            if (selected) {
                Flashers=check3;
            }else{
                Flashers=null;
            }
            boolean selected1 = jCheckBox2.isSelected();
            if (selected) {
                RemotControol=Remote;
            }else{
                RemotControol=null;
                
            }
            boolean selected2 = jCheckBox4.isSelected();
            if (selected) {
                other1=wifi;
            }else{
                other1=null;
            }
            boolean selected13 = jCheckBox5.isSelected();
            if (selected) {
                other2=bloototh;
            }else{
                other2=null;
                
            }
            boolean selected4 = jCheckBox5.isSelected();
            if (selected) {
                other3=usb;
            }else{
                other3=null;
            }
            String  battryVotage=txtDesigneBatreyVoltage.getText();
            String battryDeu=txtDesigneBatreyDuration.getText();
            String battryType=txtDesigneBattryType.getText();
            String lenseBrand=txtDesigneLenseBrand.getText();
            String lenseSize=txtDesigneLenseBrand.getText();
            int qty=Integer.parseInt(txtDesigneQTY.getText());
            double price=Double.parseDouble(txtDesignePrice.getText());
            CamaraDTO camara=new CamaraDTO(camaraId,brand,compuny,bodyT,colur,lenseType,pixel,Flashers,RemotControol,other1,other2,other3,battryVotage,battryDeu,battryType,lenseBrand,lenseSize,qty,price);
            boolean isUpdate=ManageCameraController.Update(camara);
            if (isUpdate) {
                JOptionPane.showMessageDialog(null,"Camara Is Update successful");
                loardAllCamaras();
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageCamera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbDesigneUpdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCamera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbDesigneUpdate;
    private javax.swing.JLabel lblDesigneID;
    private javax.swing.JLabel lblDesigneRemove;
    private javax.swing.JLabel lblDesigneSave;
    private javax.swing.JTable tblDesigne;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtDesigneBatreyDuration;
    private javax.swing.JTextField txtDesigneBatreyVoltage;
    private javax.swing.JTextField txtDesigneBattryType;
    private javax.swing.JTextField txtDesigneBodyType;
    private javax.swing.JTextField txtDesigneBrand;
    private javax.swing.JTextField txtDesigneCamerColur;
    private javax.swing.JTextField txtDesigneID;
    private javax.swing.JTextField txtDesigneLenseBrand;
    private javax.swing.JTextField txtDesigneLenseSize;
    private javax.swing.JTextField txtDesigneLenseType;
    private javax.swing.JTextField txtDesignePixel;
    private javax.swing.JTextField txtDesignePrice;
    private javax.swing.JTextField txtDesigneQTY;
    // End of variables declaration//GEN-END:variables

    private void loardAllCategory() {
        try {
            ArrayList<String> array = ManageCameraController.getLoardAllCategory();
            for (String category : array) {
                comboCategory.addItem(category);

            }

        } catch (Exception ex) {
            Logger.getLogger(ManageCamera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loardAllCamaras() {
        try {
            ArrayList<Camara>allCamara=ManageCameraController.getAllCamaras();
            DefaultTableModel dtm=(DefaultTableModel) tblDesigne.getModel();
            dtm.setRowCount(0);
            for (Camara camaraDTO : allCamara) {
                Object[] rowDate={
                    camaraDTO.getCaId(),
                    camaraDTO.getBrand(),
                    camaraDTO.getBodyType(),
                    camaraDTO.getClour(),
                    camaraDTO.getLenseType(),
                    camaraDTO.getPixels(),
                    camaraDTO.getLenseBrand(),
                    camaraDTO.getLenseSize(),
                    camaraDTO.getPrice(),
                    camaraDTO.getQty()
                };
                dtm.addRow(rowDate);
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageCamera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
