/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.angelStudio.view;

import java.io.InputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.edu.angelStudio.controller.ManagePrintController;
import lk.ijse.edu.angelStudio.dbConnection.DBConnection;
import lk.ijse.edu.angelStudio.entity.Print;
import lk.ijse.edu.angleStudio.model.PrintDTO;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Oshadi
 */
public class ManagePrint extends javax.swing.JFrame {

    /**
     * Creates new form ManagePhoto
     */
    public ManagePrint() {
        initComponents();
        setLocationRelativeTo(null);
        looodAllPrint();
        tblPrint.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                
                if (tblPrint.getSelectedRow() == -1) {
                    return;
                }
                txtPrintID.setText((String) tblPrint.getValueAt(tblPrint.getSelectedRow(), 0));
                txtPrintName.setText((String) tblPrint.getValueAt(tblPrint.getSelectedRow(), 1));
                txtPrintType.setText(tblPrint.getValueAt(tblPrint.getSelectedRow(), 2).toString());
                txtPrintSize.setText(tblPrint.getValueAt(tblPrint.getSelectedRow(), 3).toString());
                txtPrintPrice.setText(tblPrint.getValueAt(tblPrint.getSelectedRow(), 4).toString());
                txtPrintQty.setText(tblPrint.getValueAt(tblPrint.getSelectedRow(), 5).toString());
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPrintReport = new javax.swing.JLabel();
        txtPrintID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrintName = new javax.swing.JTextField();
        txtPrintType = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrintSize = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrintPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrintQty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblPrintID = new javax.swing.JLabel();
        lblPrintName = new javax.swing.JLabel();
        lblPrintSave = new javax.swing.JLabel();
        lblPrintUpdate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrint = new javax.swing.JTable();
        lblPrintRemove = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(59, 163, 163));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Print");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        lblPrintReport.setBackground(new java.awt.Color(0, 204, 204));
        lblPrintReport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrintReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrintReport.setText("Get Report");
        lblPrintReport.setOpaque(true);
        lblPrintReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrintReportMouseClicked(evt);
            }
        });
        jPanel1.add(lblPrintReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, 100, 30));

        txtPrintID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrintIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrintID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Print Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 30));

        txtPrintName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrintNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrintName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 190, 30));

        txtPrintType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrintTypeActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrintType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 220, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Print Type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Print Size");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 30));

        txtPrintSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrintSizeActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrintSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Print Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 30));

        txtPrintPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrintPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrintPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Qty On Hand");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 30));

        txtPrintQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrintQtyActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrintQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 220, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Print ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 30));

        lblPrintID.setBackground(new java.awt.Color(0, 204, 204));
        lblPrintID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrintID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrintID.setText("S");
        lblPrintID.setOpaque(true);
        jPanel1.add(lblPrintID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 30, 30));

        lblPrintName.setBackground(new java.awt.Color(0, 204, 204));
        lblPrintName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrintName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrintName.setText("S");
        lblPrintName.setOpaque(true);
        jPanel1.add(lblPrintName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 30, 30));

        lblPrintSave.setBackground(new java.awt.Color(0, 204, 204));
        lblPrintSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrintSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrintSave.setText("Save");
        lblPrintSave.setOpaque(true);
        lblPrintSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrintSaveMouseClicked(evt);
            }
        });
        jPanel1.add(lblPrintSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, 30));

        lblPrintUpdate.setBackground(new java.awt.Color(0, 204, 204));
        lblPrintUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrintUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrintUpdate.setText("Update");
        lblPrintUpdate.setOpaque(true);
        lblPrintUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrintUpdateMouseClicked(evt);
            }
        });
        jPanel1.add(lblPrintUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 100, 30));

        tblPrint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Print ID", "Print Name", "Print Type", "Print Size", "Print Price", "Qty On Hand"
            }
        ));
        jScrollPane1.setViewportView(tblPrint);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 580, 290));

        lblPrintRemove.setBackground(new java.awt.Color(0, 204, 204));
        lblPrintRemove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrintRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrintRemove.setText("Remove");
        lblPrintRemove.setOpaque(true);
        lblPrintRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrintRemoveMouseClicked(evt);
            }
        });
        jPanel1.add(lblPrintRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPrintRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintRemoveMouseClicked
        try {
            if (tblPrint.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Select A Row");
            }
            boolean isDelect = ManagePrintController.delete(tblPrint.getValueAt(tblPrint.getSelectedRow(), 0).toString());
            if (isDelect) {
                JOptionPane.showMessageDialog(null, "Delete A Row");
                looodAllPrint();
                txt();
            }
        } catch (Exception ex) {
            Logger.getLogger(ManagePrint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblPrintRemoveMouseClicked

    private void lblPrintSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintSaveMouseClicked
        try {
            String id = txtPrintID.getText();
            String name = txtPrintName.getText();
            String yrpe = txtPrintType.getText();
            String size = txtPrintSize.getText();
            double price = Double.parseDouble(txtPrintPrice.getText());
            int qty = Integer.parseInt(txtPrintQty.getText());
            PrintDTO print = new PrintDTO(id, name, yrpe, size, price, qty);
            boolean isAdded = ManagePrintController.add(print);
            if (isAdded) {
                JOptionPane.showMessageDialog(null, "Add NEdw Print");
                looodAllPrint();
                txt();
            }
        } catch (Exception ex) {
            Logger.getLogger(ManagePrint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblPrintSaveMouseClicked

    private void lblPrintUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintUpdateMouseClicked
        try {
            String id = txtPrintID.getText();
            String name = txtPrintName.getText();
            String yrpe = txtPrintType.getText();
            String size = txtPrintSize.getText();
            double price = Double.parseDouble(txtPrintPrice.getText());
            int qty = Integer.parseInt(txtPrintQty.getText());
            PrintDTO print = new PrintDTO(id, name, yrpe, size, price, qty);
            boolean isUpdate = ManagePrintController.update(print);
            if (isUpdate) {
                JOptionPane.showMessageDialog(null, "Update A Print");
                looodAllPrint();
                txt();
            }
        } catch (Exception ex) {
            Logger.getLogger(ManagePrint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblPrintUpdateMouseClicked

    private void txtPrintIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrintIDActionPerformed
        txtPrintName.requestFocusInWindow();
    }//GEN-LAST:event_txtPrintIDActionPerformed

    private void txtPrintNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrintNameActionPerformed
        txtPrintType.requestFocusInWindow();
    }//GEN-LAST:event_txtPrintNameActionPerformed

    private void txtPrintTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrintTypeActionPerformed
       txtPrintSize.requestFocusInWindow();
    }//GEN-LAST:event_txtPrintTypeActionPerformed

    private void txtPrintSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrintSizeActionPerformed
       txtPrintPrice.requestFocusInWindow();
    }//GEN-LAST:event_txtPrintSizeActionPerformed

    private void txtPrintPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrintPriceActionPerformed
       txtPrintQty.requestFocusInWindow();
    }//GEN-LAST:event_txtPrintPriceActionPerformed

    private void txtPrintQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrintQtyActionPerformed
       try {
            String id = txtPrintID.getText();
            String name = txtPrintName.getText();
            String yrpe = txtPrintType.getText();
            String size = txtPrintSize.getText();
            double price = Double.parseDouble(txtPrintPrice.getText());
            int qty = Integer.parseInt(txtPrintQty.getText());
            PrintDTO print = new PrintDTO(id, name, yrpe, size, price, qty);
            boolean isAdded = ManagePrintController.add(print);
            if (isAdded) {
                JOptionPane.showMessageDialog(null, "Add NEdw Print");
                looodAllPrint();
                txt();
            }
        } catch (Exception ex) {
            Logger.getLogger(ManagePrint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPrintQtyActionPerformed

    private void lblPrintReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintReportMouseClicked

//        try {
//            InputStream inputStream = getClass().getResourceAsStream("qqqq//print");
//            HashMap map = new HashMap();
//            JasperPrint jasperPrint = null;
//            jasperPrint = JasperFillManager.fillReport(inputStream, map, DBConnection.getInstance().getConnection());
//            JasperViewer.viewReport(jasperPrint,false);
//        } catch (JRException ex) {
//            Logger.getLogger(ManagePrint.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(ManagePrint.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(ManagePrint.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
    }//GEN-LAST:event_lblPrintReportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrintID;
    private javax.swing.JLabel lblPrintName;
    private javax.swing.JLabel lblPrintRemove;
    private javax.swing.JLabel lblPrintReport;
    private javax.swing.JLabel lblPrintSave;
    private javax.swing.JLabel lblPrintUpdate;
    private javax.swing.JTable tblPrint;
    private javax.swing.JTextField txtPrintID;
    private javax.swing.JTextField txtPrintName;
    private javax.swing.JTextField txtPrintPrice;
    private javax.swing.JTextField txtPrintQty;
    private javax.swing.JTextField txtPrintSize;
    private javax.swing.JTextField txtPrintType;
    // End of variables declaration//GEN-END:variables

    private void looodAllPrint() {
        try {
            ArrayList<Print> allPrint = ManagePrintController.getAll();
            DefaultTableModel dtm = (DefaultTableModel) tblPrint.getModel();
            dtm.setRowCount(0);
            for (Print print : allPrint) {
                Object[] rowData = {
                    print.getPrid(),
                    print.getName(),
                    print.getType(),
                    print.getSize(),
                    print.getPrice(),
                    print.getQty()
                
                };
                
                dtm.addRow(rowData);
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ManagePrint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void txt() {
        txtPrintID.setText("");
        txtPrintName.setText("");
        txtPrintType.setText("");
        txtPrintSize.setText("");
        txtPrintPrice.setText("");
        txtPrintQty.setText("");
    }
}
